package com.fec.xjoneproject.ui.task.electronic;

import android.view.View;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.ImageButton;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RadioButton;
import android.widget.RadioGroup;
import android.widget.ScrollView;
import android.widget.TextView;
import butterknife.ButterKnife.Finder;
import butterknife.ButterKnife.ViewBinder;
import com.fec.xjoneproject.ui.view.RequiredTextView;
import com.hbfec.xjoneproject.R;
import com.rengwuxian.materialedittext.MaterialEditText;

public class ElectronicAddFeedFragment$$ViewBinder<T extends ElectronicAddFeedFragment> implements ViewBinder<T> {
    public void bind(Finder finder, T target, Object source) {
        target.mBackView = (ImageButton) finder.castView((View) finder.findRequiredView(source, R.id.ibtn_back, "field 'mBackView'"), R.id.ibtn_back, "field 'mBackView'");
        target.mTitle = (TextView) finder.castView((View) finder.findRequiredView(source, R.id.tv_title, "field 'mTitle'"), R.id.tv_title, "field 'mTitle'");
        target.mIdNumberTv = (TextView) finder.castView((View) finder.findRequiredView(source, R.id.tv_check_electronic_idnum, "field 'mIdNumberTv'"), R.id.tv_check_electronic_idnum, "field 'mIdNumberTv'");
        target.mTelNumberTv = (TextView) finder.castView((View) finder.findRequiredView(source, R.id.tv_check_electronic_tel, "field 'mTelNumberTv'"), R.id.tv_check_electronic_tel, "field 'mTelNumberTv'");
        target.mPhotoIv = (ImageView) finder.castView((View) finder.findRequiredView(source, R.id.iv_electricitydetai_photo, "field 'mPhotoIv'"), R.id.iv_electricitydetai_photo, "field 'mPhotoIv'");
        target.mUserNameTv = (TextView) finder.castView((View) finder.findRequiredView(source, R.id.tv_check_electronic_name, "field 'mUserNameTv'"), R.id.tv_check_electronic_name, "field 'mUserNameTv'");
        target.mMeterNumberTv = (TextView) finder.castView((View) finder.findRequiredView(source, R.id.tv_check_electronic_meternum, "field 'mMeterNumberTv'"), R.id.tv_check_electronic_meternum, "field 'mMeterNumberTv'");
        target.mAddressTv = (TextView) finder.castView((View) finder.findRequiredView(source, R.id.tv_check_electronic_address, "field 'mAddressTv'"), R.id.tv_check_electronic_address, "field 'mAddressTv'");
        target.mTime1Tv = (TextView) finder.castView((View) finder.findRequiredView(source, R.id.tv_check_electronic_time1, "field 'mTime1Tv'"), R.id.tv_check_electronic_time1, "field 'mTime1Tv'");
        target.mDegree1Tv = (TextView) finder.castView((View) finder.findRequiredView(source, R.id.tv_check_electronic_degree1, "field 'mDegree1Tv'"), R.id.tv_check_electronic_degree1, "field 'mDegree1Tv'");
        target.mTime2Tv = (TextView) finder.castView((View) finder.findRequiredView(source, R.id.tv_check_electronic_time2, "field 'mTime2Tv'"), R.id.tv_check_electronic_time2, "field 'mTime2Tv'");
        target.mDegree2Tv = (TextView) finder.castView((View) finder.findRequiredView(source, R.id.tv_check_electronic_degree2, "field 'mDegree2Tv'"), R.id.tv_check_electronic_degree2, "field 'mDegree2Tv'");
        target.mTime3Tv = (TextView) finder.castView((View) finder.findRequiredView(source, R.id.tv_check_electronic_time3, "field 'mTime3Tv'"), R.id.tv_check_electronic_time3, "field 'mTime3Tv'");
        target.mDegree3Tv = (TextView) finder.castView((View) finder.findRequiredView(source, R.id.tv_check_electronic_degree3, "field 'mDegree3Tv'"), R.id.tv_check_electronic_degree3, "field 'mDegree3Tv'");
        target.mNormalAverageTv = (TextView) finder.castView((View) finder.findRequiredView(source, R.id.tv_check_electronic_normalaverage, "field 'mNormalAverageTv'"), R.id.tv_check_electronic_normalaverage, "field 'mNormalAverageTv'");
        target.mCheckCardTextView = (TextView) finder.castView((View) finder.findRequiredView(source, R.id.rtv_check_card, "field 'mCheckCardTextView'"), R.id.rtv_check_card, "field 'mCheckCardTextView'");
        target.mIdNumberEt = (MaterialEditText) finder.castView((View) finder.findRequiredView(source, R.id.et_check_idnum_note, "field 'mIdNumberEt'"), R.id.et_check_idnum_note, "field 'mIdNumberEt'");
        target.mCheckPhoneTextView = (TextView) finder.castView((View) finder.findRequiredView(source, R.id.rtv_check_phone, "field 'mCheckPhoneTextView'"), R.id.rtv_check_phone, "field 'mCheckPhoneTextView'");
        target.mTelNumberEt = (MaterialEditText) finder.castView((View) finder.findRequiredView(source, R.id.et_check_tel_note, "field 'mTelNumberEt'"), R.id.et_check_tel_note, "field 'mTelNumberEt'");
        target.mCheckAddressTextView = (TextView) finder.castView((View) finder.findRequiredView(source, R.id.rtv_check_address, "field 'mCheckAddressTextView'"), R.id.rtv_check_address, "field 'mCheckAddressTextView'");
        target.mRealAddressTv = (TextView) finder.castView((View) finder.findRequiredView(source, R.id.et_check_electronic_realaddress, "field 'mRealAddressTv'"), R.id.et_check_electronic_realaddress, "field 'mRealAddressTv'");
        target.mDetailAddressEt = (MaterialEditText) finder.castView((View) finder.findRequiredView(source, R.id.et_check_electronic_detailaddress, "field 'mDetailAddressEt'"), R.id.et_check_electronic_detailaddress, "field 'mDetailAddressEt'");
        target.mHaveToolLinearLayout = (LinearLayout) finder.castView((View) finder.findRequiredView(source, R.id.ll_have_tool, "field 'mHaveToolLinearLayout'"), R.id.ll_have_tool, "field 'mHaveToolLinearLayout'");
        target.mReasonLinearLayout = (LinearLayout) finder.castView((View) finder.findRequiredView(source, R.id.ll_reason, "field 'mReasonLinearLayout'"), R.id.ll_reason, "field 'mReasonLinearLayout'");
        target.mHaveToolRbtn = (RadioButton) finder.castView((View) finder.findRequiredView(source, R.id.rb_electricityfeedback_havetool, "field 'mHaveToolRbtn'"), R.id.rb_electricityfeedback_havetool, "field 'mHaveToolRbtn'");
        target.mNotHaveToolRbtn = (RadioButton) finder.castView((View) finder.findRequiredView(source, R.id.rb_electricityfeedback_nothavetool, "field 'mNotHaveToolRbtn'"), R.id.rb_electricityfeedback_nothavetool, "field 'mNotHaveToolRbtn'");
        target.mNewDeviceCb = (CheckBox) finder.castView((View) finder.findRequiredView(source, R.id.cb_electricityfeedback_reason_newdevice, "field 'mNewDeviceCb'"), R.id.cb_electricityfeedback_reason_newdevice, "field 'mNewDeviceCb'");
        target.mDecorationCb = (CheckBox) finder.castView((View) finder.findRequiredView(source, R.id.cb_electricityfeedback_reason_decoration, "field 'mDecorationCb'"), R.id.cb_electricityfeedback_reason_decoration, "field 'mDecorationCb'");
        target.mFarmingCb = (CheckBox) finder.castView((View) finder.findRequiredView(source, R.id.cb_electricityfeedback_reason_farming, "field 'mFarmingCb'"), R.id.cb_electricityfeedback_reason_farming, "field 'mFarmingCb'");
        target.mInlegalDeviceCb = (CheckBox) finder.castView((View) finder.findRequiredView(source, R.id.cb_electricityfeedback_reason_inlegaldevice, "field 'mInlegalDeviceCb'"), R.id.cb_electricityfeedback_reason_inlegaldevice, "field 'mInlegalDeviceCb'");
        target.mSuspiciousCb = (CheckBox) finder.castView((View) finder.findRequiredView(source, R.id.cb_electricityfeedback_reason_suspicious, "field 'mSuspiciousCb'"), R.id.cb_electricityfeedback_reason_suspicious, "field 'mSuspiciousCb'");
        target.mOtherReasonCb = (CheckBox) finder.castView((View) finder.findRequiredView(source, R.id.cb_electricityfeedback_reason_otherreason, "field 'mOtherReasonCb'"), R.id.cb_electricityfeedback_reason_otherreason, "field 'mOtherReasonCb'");
        target.mNoteEt = (MaterialEditText) finder.castView((View) finder.findRequiredView(source, R.id.et_check_population_note, "field 'mNoteEt'"), R.id.et_check_population_note, "field 'mNoteEt'");
        target.mNeedSurveyYesRbtn = (RadioButton) finder.castView((View) finder.findRequiredView(source, R.id.rb_electricityfeedback_needsurvey_yes, "field 'mNeedSurveyYesRbtn'"), R.id.rb_electricityfeedback_needsurvey_yes, "field 'mNeedSurveyYesRbtn'");
        target.mNeedSurveyNoRbtn = (RadioButton) finder.castView((View) finder.findRequiredView(source, R.id.rb_electricityfeedback_needsurvey_no, "field 'mNeedSurveyNoRbtn'"), R.id.rb_electricityfeedback_needsurvey_no, "field 'mNeedSurveyNoRbtn'");
        target.mPolice = (RadioGroup) finder.castView((View) finder.findRequiredView(source, R.id.rg_electricityfeedback_needsurvey, "field 'mPolice'"), R.id.rg_electricityfeedback_needsurvey, "field 'mPolice'");
        target.mSaveBtn = (Button) finder.castView((View) finder.findRequiredView(source, R.id.btn_save, "field 'mSaveBtn'"), R.id.btn_save, "field 'mSaveBtn'");
        target.mPostBtn = (Button) finder.castView((View) finder.findRequiredView(source, R.id.btn_post, "field 'mPostBtn'"), R.id.btn_post, "field 'mPostBtn'");
        target.mPoliceReasonEt = (MaterialEditText) finder.castView((View) finder.findRequiredView(source, R.id.tv_reason_need_police, "field 'mPoliceReasonEt'"), R.id.tv_reason_need_police, "field 'mPoliceReasonEt'");
        target.mRealAddressErrorLayout = (LinearLayout) finder.castView((View) finder.findRequiredView(source, R.id.ll_real_address_error, "field 'mRealAddressErrorLayout'"), R.id.ll_real_address_error, "field 'mRealAddressErrorLayout'");
        target.mHaveToolErrorLayout = (LinearLayout) finder.castView((View) finder.findRequiredView(source, R.id.ll_have_tool_error, "field 'mHaveToolErrorLayout'"), R.id.ll_have_tool_error, "field 'mHaveToolErrorLayout'");
        target.mReasonErrorLayout = (LinearLayout) finder.castView((View) finder.findRequiredView(source, R.id.ll_reason_error, "field 'mReasonErrorLayout'"), R.id.ll_reason_error, "field 'mReasonErrorLayout'");
        target.mNeedSurveyErrorLayout = (LinearLayout) finder.castView((View) finder.findRequiredView(source, R.id.ll_need_survey_error, "field 'mNeedSurveyErrorLayout'"), R.id.ll_need_survey_error, "field 'mNeedSurveyErrorLayout'");
        target.mPoliceLayout = (LinearLayout) finder.castView((View) finder.findRequiredView(source, R.id.ll_police, "field 'mPoliceLayout'"), R.id.ll_police, "field 'mPoliceLayout'");
        target.mPoliceReasonMaterialRequiredTextView = (RequiredTextView) finder.castView((View) finder.findRequiredView(source, R.id.rtv_reason_need_police, "field 'mPoliceReasonMaterialRequiredTextView'"), R.id.rtv_reason_need_police, "field 'mPoliceReasonMaterialRequiredTextView'");
        target.mScrollView = (ScrollView) finder.castView((View) finder.findRequiredView(source, R.id.scrollView, "field 'mScrollView'"), R.id.scrollView, "field 'mScrollView'");
    }

    public void unbind(T target) {
        target.mBackView = null;
        target.mTitle = null;
        target.mIdNumberTv = null;
        target.mTelNumberTv = null;
        target.mPhotoIv = null;
        target.mUserNameTv = null;
        target.mMeterNumberTv = null;
        target.mAddressTv = null;
        target.mTime1Tv = null;
        target.mDegree1Tv = null;
        target.mTime2Tv = null;
        target.mDegree2Tv = null;
        target.mTime3Tv = null;
        target.mDegree3Tv = null;
        target.mNormalAverageTv = null;
        target.mCheckCardTextView = null;
        target.mIdNumberEt = null;
        target.mCheckPhoneTextView = null;
        target.mTelNumberEt = null;
        target.mCheckAddressTextView = null;
        target.mRealAddressTv = null;
        target.mDetailAddressEt = null;
        target.mHaveToolLinearLayout = null;
        target.mReasonLinearLayout = null;
        target.mHaveToolRbtn = null;
        target.mNotHaveToolRbtn = null;
        target.mNewDeviceCb = null;
        target.mDecorationCb = null;
        target.mFarmingCb = null;
        target.mInlegalDeviceCb = null;
        target.mSuspiciousCb = null;
        target.mOtherReasonCb = null;
        target.mNoteEt = null;
        target.mNeedSurveyYesRbtn = null;
        target.mNeedSurveyNoRbtn = null;
        target.mPolice = null;
        target.mSaveBtn = null;
        target.mPostBtn = null;
        target.mPoliceReasonEt = null;
        target.mRealAddressErrorLayout = null;
        target.mHaveToolErrorLayout = null;
        target.mReasonErrorLayout = null;
        target.mNeedSurveyErrorLayout = null;
        target.mPoliceLayout = null;
        target.mPoliceReasonMaterialRequiredTextView = null;
        target.mScrollView = null;
    }
}
